--- #YAML:1.0
name:               Chemistry-RECAP
version:            0.01
abstract:           Cleave compound RECAP Rules
author:
    - kzfm <kerolinq@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Chemistry::File::SMARTS:  0
    Chemistry::Ring:      0
    Test::More:           0
    UNIVERSAL::require:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
